export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_CATEGORIES_REQ = "GET_CATEGORIES_REQ";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const GET_PRODUCTS_BY_CATEGORY_REQ = "GET_PRODUCTS_BY_CATEGORY_REQ";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORY_ERROR = "GET_CATEGORIES_ERROR";

export const GET_PRODUCT_BY_ID_REQ = "GET_PRODUCT_BY_ID_REQ";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_ERROR = "GET_PRODUCT_BY_ID_ERROR";

export const LOAD_MORE_REQ = "LOAD_MORE_REQ";
export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS";
export const LOAD_MORE_ERROR = "LOAD_MORE_ERROR";
